databases:
  - name: velora-db
    databaseName: velora
    user: velora
    plan: free

services:
  - type: web
    name: velora
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: velora-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
